import type { Metadata } from "next";
import localFont from 'next/font/local'

// import { Amiri_Quran } from 'next/font/google';
import "./globals.css";

// const ArabicSans = Amiri_Quran({
//   subsets: ["arabic"],
//   variable: "--font-arabic-sans",
//   weight: ["400"],
// })
const ArabicSans = localFont({
  src: "./fonts/KFGQPC Uthmanic Script HAFS Regular.otf",
  variable: "--font-arabic-sans",
  weight: "100 900",
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${ArabicSans.className} antialiased bg-zinc-50 dark:bg-zinc-950`}
      >
        {children}
      </body>
    </html>
  );
}
